name: Trojan Book Builder
author: Aaron Lun
description: Create a trojan package to sneak books onto the Bioconductor build system.
inputs:
  book:
    description: 'Full name of the GitHub repository containing the book, e.g., Bioconductor/OrchestratingSingleCellAnalysis.'
    required: true
  branch:
    description: 'Name of the branch to use. Defaults to master.'
    required: false
    default: "master"
  biocViews:
    description: 'Comma-seperated terms to use in the biocViews field.'
    required: false
    default: "Workflow"
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.book }}
    - ${{ inputs.branch }}
    - ${{ inputs.biocViews }}
